# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rx74LtKa9VQrmGbymlMdRzUw3wOM7-zM
"""

import numpy as np
import pandas as pd

def impute_by_min(country):
    country__data = data[data["country"] == country]
    min_vaccinations = country__data["daily_vaccinations"].min()
    data.loc[(data["country"] == country) & (data["daily_vaccinations"].isna()), "daily_vaccinations"] = min_vaccinations
    data.loc[(data["country"] == country) & (data["daily_vaccinations"].isnull()), "daily_vaccinations"] = 0

countries = data["country"].unique()
for country in countries:
    impute_by_min(country)